name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn install

    - name: Publish Snapshots to Maven Central
      if: ${{ env.PUSH_PACKAGES }}
      run: ./.github/scripts/publish.sh
      env:
        GPG_ENCPASS: ${{ secrets.GPG_ENCPASS }}
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
